import { PokemonSpecies } from '../../domain/pokemon-species';
import { LoreEntry, LoreEntryWithFallback } from '../../domain/lore';
import rawLoreData from './lore-data.json';

const LORE_BY_SPECIES_ID = new Map(
  (rawLoreData as LoreEntry[]).map((entry) => [entry.speciesId, entry]),
);

export function getLoreForSpecies(speciesId: number): LoreEntry | undefined {
  const writtenLore = LORE_BY_SPECIES_ID.get(speciesId);
  if (writtenLore) {
    return writtenLore;
  }
  return undefined;
}

export function getLoreWithFallback(
  species: PokemonSpecies | undefined,
): LoreEntryWithFallback {
  if (!species) {
    return {
      speciesId: 0,
      origin: 'Species data not found.',
      goRelevance: '',
      battleTip: '',
      easterEgg: '',
      goDifference: '',
      evolutionCost: '',
      shinyRate: '',
      isAutoGenerated: true,
    };
  }

  const writtenLore = LORE_BY_SPECIES_ID.get(species.id);
  if (writtenLore) {
    return { ...writtenLore, isAutoGenerated: false };
  }

  const maxStat = Math.max(species.baseAttack, species.baseDefense, species.baseStamina);
  let battleRole = 'versatil';
  if (maxStat === species.baseAttack) battleRole = 'ofensivo (ATK)';
  else if (maxStat === species.baseDefense) battleRole = 'defensivo (DEF)';
  else battleRole = 'tanque (STA)';

  const candyEstimate = species.id <= 151 ? 50 : 125;

  return {
    speciesId: species.id,
    origin: `Um Pokemon do tipo ${species.types.join('/')} da Geracao ${species.generation}. Seu nome e ${species.name}.`,
    goRelevance: `Tem ATK base ${species.baseAttack}, DEF ${species.baseDefense} e STA ${species.baseStamina}. E mais ${battleRole}.`,
    battleTip: `Seu melhor atributo e ${maxStat} (${battleRole}). Use moves que aproveitem seu typing ${species.types.join('/')}.`,
    easterEgg: `Foi introduzido na Geracao ${species.generation}. Complete a Pokedex para mais informacoes.`,
    goDifference: 'Consulte fontes da comunidade como PvPoke e PoGo API para analises detalhadas de moveset e ranking.',
    evolutionCost: `Aproximadamente ${candyEstimate} candy para evolucoes. Buddy 3km/candy.`,
    shinyRate: 'Shiny rate padrao (~1/500). Consulte eventos ativos para chances aumentadas.',
    isAutoGenerated: true,
  };
}
