import { getLoreForSpecies, getLoreWithFallback } from './loreRepository';
import { PokemonSpecies } from '../../domain/pokemon-species';

const BULBASAUR: PokemonSpecies = {
  id: 1,
  name: 'Bulbasaur',
  generation: 1,
  types: ['Grass', 'Poison'],
  baseAttack: 118,
  baseDefense: 111,
  baseStamina: 128,
};

const UNSEEDED_SPECIES: PokemonSpecies = {
  id: 999999,
  name: 'Testmon',
  generation: 9,
  types: ['Normal'],
  baseAttack: 100,
  baseDefense: 100,
  baseStamina: 100,
};

describe('loreRepository', () => {
  it.each(['pt-BR', 'en', 'es'] as const)('returns hand-written lore for species 1 in %s', (language) => {
    const lore = getLoreForSpecies(1, language);
    expect(lore).toBeDefined();
    expect(lore!.origin.trim().length).toBeGreaterThan(0);
    expect(lore!.goRelevance.trim().length).toBeGreaterThan(0);
  });

  it.each(['pt-BR', 'en', 'es'] as const)('getLoreWithFallback marks written lore as not auto-generated in %s', (language) => {
    const lore = getLoreWithFallback(BULBASAUR, language);
    expect(lore.isAutoGenerated).toBe(false);
    expect(lore.speciesId).toBe(1);
  });

  it('falls back to a procedural entry for a species with no written lore', () => {
    const lore = getLoreWithFallback(UNSEEDED_SPECIES, 'en');
    expect(lore.isAutoGenerated).toBe(true);
    expect(lore.origin).toContain('Generation 9');
    expect(lore.origin).toContain('Testmon');
  });

  it('localizes the procedural fallback per language', () => {
    const pt = getLoreWithFallback(UNSEEDED_SPECIES, 'pt-BR');
    const es = getLoreWithFallback(UNSEEDED_SPECIES, 'es');
    const en = getLoreWithFallback(UNSEEDED_SPECIES, 'en');
    expect(pt.origin).toContain('Geracao 9');
    expect(es.origin).toContain('Generacion 9');
    expect(en.origin).toContain('Generation 9');
  });

  it('returns a localized message when species is undefined', () => {
    const lore = getLoreWithFallback(undefined, 'es');
    expect(lore.origin).toBe('Datos de la especie no encontrados.');
  });
});
