export interface TimelineEvent {
  /** e.g. "Generation I (1996)" or "Anime debut" — kept short, this renders as a small header. */
  label: string;
  note: string;
}

export interface LoreEntry {
  speciesId: number;
<<<<<<< HEAD
  origin: string;
  goRelevance: string;
  battleTip: string;
  easterEgg: string;
  goDifference: string;
  evolutionCost: string;
  shinyRate: string;
}

export interface LoreEntryWithFallback extends LoreEntry {
  isAutoGenerated: boolean;
=======
  /** Shown first, before the trainer chooses to dig deeper. Keep this to one or two sentences. */
  summary: string;
  timeline: readonly TimelineEvent[];
  curiosities: readonly string[];
>>>>>>> 18b789e050f190694e288b5d56b3774ac32cb891
}
