export interface LoreEntry {
  speciesId: number;
  origin: string;
  goRelevance: string;
  battleTip: string;
  easterEgg: string;
  goDifference: string;
  evolutionCost: string;
  shinyRate: string;
}

export interface LoreEntryWithFallback extends LoreEntry {
  isAutoGenerated: boolean;
}
