export type SupportedLanguage = 'en' | 'pt-BR' | 'es';

export const SUPPORTED_LANGUAGES: readonly SupportedLanguage[] = ['en', 'pt-BR', 'es'];

export const LANGUAGE_LABELS: Record<SupportedLanguage, string> = {
  en: 'English',
  'pt-BR': 'Português',
  es: 'Español',
};

/** Every translatable string in the app, as a flat dictionary keyed by dot-path. Every language
 * file must implement exactly this shape — a missing key is a compile error, not a silent
 * runtime fallback, so translations can't quietly drift out of sync as new UI ships. */
export interface TranslationKeys {
  'nav.pokedex': string;
  'nav.tools': string;
  'nav.rankings': string;
  'nav.quiz': string;
  'nav.more': string;

  'pokedex.title': string;
  'pokedex.searchPlaceholder': string;
  'pokedex.allGens': string;
  'pokedex.allTypes': string;
  'pokedex.pickerTitle': string;
  'pokedex.emptyResults': string;
  'pokedex.quickActions': string;
  'pokedex.filterByGen': string;
  'pokedex.filterByType': string;

  'tools.title': string;
  'tools.subtitle': string;
  'tools.ivCalculator.title': string;
  'tools.ivCalculator.description': string;
  'tools.compare.title': string;
  'tools.compare.description': string;
  'tools.typeChart.title': string;
  'tools.typeChart.description': string;
  'tools.raidCounters.title': string;
  'tools.raidCounters.description': string;

  'more.title': string;
  'more.overlayDemo.title': string;
  'more.overlayDemo.description': string;
  'more.language': string;
  'more.footer': string;

  'common.change': string;
  'common.retry': string;
  'common.close': string;
  'common.calculate': string;
  'common.loading': string;

  'companion.askAi': string;
  'companion.askAgain': string;
  'companion.retryAskAi': string;
  'companion.choosePrompt': string;
  'companion.searchPlaceholder': string;
  'companion.dialogueAbout': string;
  'companion.dialogueInGo': string;
  'companion.dialogueBattleTip': string;
  'companion.dialogueFunFact': string;
  'companion.dialogueAiTip': string;

  'pvpLeague.great': string;
  'pvpLeague.ultra': string;
  'pvpLeague.master': string;

  'metaTier.top': string;
  'metaTier.viable': string;
  'metaTier.niche': string;

  'bulkTier.elite': string;
  'bulkTier.great': string;
  'bulkTier.aboveAverage': string;
  'bulkTier.belowAverage': string;
  'bulkTier.fragile': string;

  'detail.speciesNotFound': string;
  'detail.generation': string;
  'detail.baseStats': string;
  'detail.bestMoveset': string;
  'detail.notRankedPvp': string;
  'detail.pvpSource': string;
  'detail.battleRole': string;
  'detail.attack': string;
  'detail.defense': string;
  'detail.notRankedAttacking': string;
  'detail.bulkUnavailable': string;
  'detail.bestPvpScore': string;
  'detail.tankierThan': string;
  'detail.roleSourceNote': string;
  'detail.powerUpCost': string;
  'detail.fromLevel': string;
  'detail.toLevel': string;
  'detail.stardust': string;
  'detail.candy': string;
  'detail.xlCandy': string;
  'detail.powerUpHint': string;
  'detail.loreTitle': string;
  'detail.autoGenerated': string;
  'detail.lore.origin': string;
  'detail.lore.goRelevance': string;
  'detail.lore.battleTip': string;
  'detail.lore.easterEgg': string;
  'detail.lore.goDifference': string;
  'detail.lore.evolutionCost': string;
  'detail.lore.shinyRate': string;
  'detail.evolutionChainButton': string;
  'detail.calculateIvButton': string;

  'ivCalc.title': string;
  'ivCalc.species': string;
  'ivCalc.unknownSpecies': string;
  'ivCalc.cp': string;
  'ivCalc.hp': string;
  'ivCalc.minLevel': string;
  'ivCalc.maxLevel': string;
  'ivCalc.calculate': string;
  'ivCalc.errorCpHp': string;
  'ivCalc.errorLevel': string;
  'ivCalc.errorMinMax': string;
  'ivCalc.errorGeneric': string;
  'ivCalc.noMatches': string;
  'ivCalc.combinationsCountSingular': string;
  'ivCalc.combinationsCountPlural': string;
  'ivCalc.resultLevel': string;

  'compare.pokemonA': string;
  'compare.pokemonB': string;
  'compare.bulkLabel': string;
  'compare.sourceNote': string;

  'typeChart.hint': string;
  'typeChart.superEffective': string;
  'typeChart.notVeryEffective': string;
  'typeChart.noEffect': string;
  'typeChart.neutral': string;

  'rankings.emptyText': string;
  'rankings.category.attack': string;
  'rankings.category.defense': string;
  'rankings.category.stamina': string;
  'rankings.category.bulk': string;
  'rankings.category.cp': string;
  'rankings.category.pvpGreat': string;
  'rankings.category.pvpUltra': string;
  'rankings.category.pvpMaster': string;

  'raid.hint': string;
  'raid.tierRaids': string;
  'raid.weather': string;
  'raid.topCountersVs': string;
  'raid.estDps': string;
  'raid.boosted': string;

  'weather.any': string;
  'weather.Clear': string;
  'weather.Sunny': string;
  'weather.Rain': string;
  'weather.PartlyCloudy': string;
  'weather.Cloudy': string;
  'weather.Windy': string;
  'weather.Snow': string;
  'weather.Fog': string;

  'evolution.empty': string;
  'evolution.candy': string;

  'quiz.notEnoughData': string;
  'quiz.progress': string;
  'quiz.complete': string;
  'quiz.playAgain': string;
  'quiz.nextQuestion': string;
  'quiz.seeResults': string;
  'quiz.scorePerfect': string;
  'quiz.scoreGreat': string;
  'quiz.scoreOkay': string;
  'quiz.scoreLow': string;

  'overlay.title': string;
  'overlay.subtitle': string;
  'overlay.pickButton': string;
  'overlay.errorText': string;
  'overlay.resultLabel': string;
  'overlay.ivUnmatched': string;
  'overlay.ivExtraMatches': string;
  'overlay.defense': string;
  'overlay.whatToDoWithIt': string;
  'overlay.askAiAboutScan': string;
  'overlay.speciesNotRecognized': string;
  'overlay.rawTextLabel': string;
  'overlay.rawTextEmpty': string;
  'overlay.aiGenericError': string;
  'aiContext.raid': string;
  'aiContext.battle': string;
  'aiContext.capture': string;
  'aiContext.levelup': string;
  'aiContext.general': string;
}
